Repository Dev-FE-2/toy-project3-team2-wefit, pull requests merged in 2025-01, with the labels that each got.

#12 chore: 라우터, 레이아웃, 폴더 구조 구성 (#7)
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/apis/.gitkeep
  src/assets/we-fit-logo.svg
  src/components/header/LogoHeader.tsx
  src/components/navigation-bar/NavigationBar.tsx
  src/constants/constants.ts
  src/hooks/.gitkeep
  src/layout/Layout.tsx
  src/mocks/.gitkeep
  src/pages/AuthorDetailPage.tsx
  src/pages/BookmarkPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/VideoAddPage.tsx
  src/pages/VideoDetailPage.tsx
  src/pages/my-page/MyPage.tsx
  src/pages/my-page/MyPageEdit.tsx
  src/pages/playlist/PlayListDetailPage.tsx
  src/pages/playlist/PlayListPage.tsx
  src/routes/Router.tsx
  src/store/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/utils/cn.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🔧 CHORE, 💻 FE

#10 [Chore]: design token 정의
  src/styles/global.css
  tailwind.config.js
Labels: 🔧 CHORE

#11 [Chore]: supabase 세팅(#8)
  package-lock.json
  package.json
  src/api/DeleteData.ts
  src/api/GetData.ts
  src/api/PatchData.ts
  src/api/PostData.ts
  src/api/Supabase.ts
Labels: 🔧 CHORE

#14 style: 디자인 토큰 값 수정 및 적용 (#13)
  src/components/header/LogoHeader.tsx
  src/components/navigation-bar/NavigationBar.tsx
  src/layout/Layout.tsx
  src/styles/global.css
  tailwind.config.js
Labels: 💻 FE, 🌴 STYLE

#18 feat: button 컴포넌트 추가 (#15)
  src/components/common/button/Button.tsx
Labels: 💻 FE, 🚀 FEAT

#20 feat: 로그인 페이지 퍼블리싱 (#19)
  src/assets/treadmill.svg
  src/layout/Layout.tsx
  src/pages/LoginPage.tsx
Labels: 💻 FE, 🚀 FEAT

#22 feat: 프로필 아이디 컴포넌트 구현 (#17)
  src/components/simple-profile/SimpleProfile.tsx
Labels: 💻 FE, 🚀 FEAT

#21 feat: label-input 컴포넌트 구현 (#21)
  src/components/common/label-input/LabelInput.tsx
  src/hooks/useDebounce.ts
Labels: 💻 FE, 🚀 FEAT

#26 feat: SplashPage 퍼블리싱 및 애니메이션 구현 (#26)
  src/constants/constants.ts
  src/pages/SplashPage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#28 feat: 목데이터 토대로 메인페이지 퍼블리싱 (#23)
  src/assets/empty-box.svg
  src/assets/thumbnail/thumbnail1.jpg
  src/assets/thumbnail/thumbnail2.jpg
  src/assets/thumbnail/thumbnail3.jpg
  src/assets/thumbnail/thumbnail4.jpg
  src/assets/thumbnail/thumbnail5.jpg
  src/assets/user/user1.png
  src/assets/user/user2.png
  src/assets/user/user3.png
  src/components/empty/EmptyResult.tsx
  src/components/simple-profile/SimpleProfile.tsx
  src/components/video/VideoCategory.tsx
  src/components/video/VideoItem.tsx
  src/components/video/VideoList.tsx
  src/components/video/VideoStats.tsx
  src/hooks/.gitkeep
  src/mocks/.gitkeep
  src/mocks/mockUsers.ts
  src/mocks/mockVideos.ts
  src/mocks/videoCategories.ts
  src/pages/HomePage.tsx
  src/types/.gitkeep
  src/types/user.ts
  src/types/video.ts
  src/utils/.gitkeep
  src/utils/formatNumber.ts
  src/utils/getTimeAgo.ts
Labels: 💻 FE, 🚀 FEAT

#31 feat: 상세 페이지 추가 라우터 구성 및 상세 페이지에 로고 대신 뒤로 가기 버튼 삽입 (#30)
  src/components/header/BackHeader.tsx
  src/components/header/LogoHeader.tsx
  src/components/navigation-bar/NavigationBar.tsx
  src/constants/constants.ts
  src/layout/Layout.tsx
  src/pages/VideoEditPage.tsx
  src/pages/bookmark/BookmarkCategoryEditPage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#27 feat: 영상 업로드 페이지 마크업 (#25)
  src/assets/thumnail-upload.svg
  src/assets/video-upload.svg
  src/components/common/label-input/LabelInput.tsx
  src/components/common/simple-profile/SimpleProfile.tsx
  src/components/video/VideoItem.tsx
  src/pages/VideoAddPage.tsx
  src/styles/global.css
Labels: 💻 FE, 🚀 FEAT

#34 feat: 작성자 상세 페이지 퍼블리싱 (#32)
  src/components/author/AuthorProfile.tsx
  src/components/video/VideoSortNav.tsx
  src/mocks/mockUsers.ts
  src/pages/AuthorDetailPage.tsx
  src/types/video.ts
Labels: 💻 FE, 🚀 FEAT

#37 style: gray 컬러에 대한 토큰 값 수정 및 스타일 수정 (#36)
  src/components/author/AuthorProfile.tsx
  src/components/common/button/Button.tsx
  src/components/common/simple-profile/SimpleProfile.tsx
  src/components/video/VideoItem.tsx
  src/components/video/VideoStats.tsx
  src/styles/global.css
Labels: 🌴 STYLE

#39 refactor: 썸네일 업로드 컴포넌트 분리 (#38)
  src/components/common/label-input/LabelInput.tsx
  src/components/thumbnail/ThumbnailUpload.tsx
  src/pages/VideoAddPage.tsx
  src/types/thumbnail.ts
Labels: 💻 FE, 🔨 REFACTOR

#40 feat: 영상 수정 페이지 마크업 (#33)
  src/components/thumbnail/ThumbnailUpload.tsx
  src/components/video/VideoUploadBox.tsx
  src/pages/VideoAddPage.tsx
  src/pages/VideoEditPage.tsx
  src/types/thumbnail.ts
Labels: 💻 FE, 🚀 FEAT

#35 feat: 북마크 페이지 마크업 (#35)
  src/components/bookmark/BookmarkCategory.tsx
  src/components/bookmark/BookmarkHeader.tsx
  src/components/bookmark/BookmarkItem.tsx
  src/components/bookmark/BookmarkList.tsx
  src/components/bookmark/BookmarkStatus.tsx
  src/components/common/simple-profile/SimpleProfile.tsx
  src/components/video/VideoList.tsx
  src/components/video/VideoStats.tsx
  src/mocks/bookmarkCategories.ts
  src/pages/bookmark/BookmarkPage.tsx
  src/types/video.ts
Labels: 💻 FE, 🚀 FEAT

#44 feat: 북마크 카테고리 추가 페이지 마크업 (#43)
  src/components/common/label-input/LabelInput.tsx
  src/components/common/simple-profile/SimpleProfile.tsx
  src/components/thumbnail/ThumbnailUpload.tsx
  src/mocks/mockVideos.ts
  src/pages/bookmark/BookmarkCategoryEditPage.tsx
  src/types/thumbnail.ts
Labels: 💻 FE, 🚀 FEAT, 🔨 REFACTOR

#46 feat: 내 정보 페이지 마크업 (#42)
  package-lock.json
  package.json
  src/assets/basil_edit-outline.svg
  src/components/my-page/MyPageProfile.tsx
  src/components/my-page/MyPageVideoItem.tsx
  src/components/my-page/MyPageVideoStats.tsx
  src/components/my-page/MyUploadVideoItem.tsx
  src/components/my-page/UploadVideoList.tsx
  src/components/my-page/WatchedVideoList.tsx
  src/constants/constants.ts
  src/pages/my-page/MyPage.tsx
  src/pages/my-page/MyUploadVideoPage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#51 refactor: 영상 상세 페이지 zustand로 상태 관리 (#49)
  package-lock.json
  package.json
  src/components/comment/CommentActions.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/VideoComment.tsx
  src/store/.gitkeep
  src/store/useCommentStore.ts
  src/types/comment.ts
Labels: 💻 FE, 🔨 REFACTOR

#48 feat: 북마크 추가 후 페이지 마크업 (#45)
  src/components/bookmark/BookmarkCategory.tsx
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/bookmark/BookmarkHeader.tsx
  src/components/bookmark/BookmarkList.tsx
  src/constants/constants.ts
  src/mocks/mockVideos.ts
  src/pages/bookmark/BookmarkPage.tsx
Labels: 💻 FE, 🚀 FEAT

#54 refactor: 내 정보 페이지 스와이퍼 적용 (#50)
  package-lock.json
  package.json
  src/components/my-page/MyPageVideoItem.tsx
  src/components/my-page/UploadVideoList.tsx
  src/components/my-page/WatchedVideoList.tsx
  src/pages/my-page/MyPage.tsx
  src/styles/global.css
Labels: 💻 FE, 🔨 REFACTOR

#58 feat: 영상 상세 페이지 댓글 파트에 댓글 추가 퍼블리싱 (#52)
  src/components/comment/CommentActions.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/VideoComment.tsx
  src/store/useCommentStore.ts
  src/types/comment.ts
Labels: 💻 FE, 🚀 FEAT

#57 feat: 내 정보 수정 페이지 마크업 (#55)
  src/assets/plus-circle.svg
  src/components/my-page/MyPageEditProfileImage.tsx
  src/components/my-page/UploadVideoList.tsx
  src/components/thumbnail/ThumbnailUpload.tsx
  src/hooks/useSelectImage.ts
  src/pages/VideoAddPage.tsx
  src/pages/VideoEditPage.tsx
  src/pages/my-page/MyPageEdit.tsx
Labels: 💻 FE, 🚀 FEAT

#56 feat: 플레이리스트 상세 페이지 마크업 (#53)
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/playlist/PlayList.tsx
  src/components/playlist/PlayListItem.tsx
  src/components/playlist/PlayListVideo.tsx
  src/mocks/mockVideos.ts
  src/pages/playlist/PlayListDetailPage.tsx
  src/types/bookmark.ts
Labels: 🚀 FEAT, 🔨 REFACTOR

#62 feat: 내가 업로드한 동영상 페이지 마크업(#59)
  src/components/my-page/MyPageUploadVideoList.tsx
  src/components/my-page/MyUploadVideoItem.tsx
  src/components/my-page/MyUploadVideoList.tsx
  src/layout/Layout.tsx
  src/pages/my-page/MyPage.tsx
  src/pages/my-page/MyUploadVideoPage.tsx
Labels: 💻 FE, 🚀 FEAT

#64 feat: supabase 소셜 로그인 연동 (#61)
  package-lock.json
  package.json
  src/api/DeleteData.ts
  src/api/GetData.ts
  src/api/PatchData.ts
  src/api/PostData.ts
  src/api/Supabase.ts
  src/api/users.ts
  src/components/auth/GoogleOAuthHandler.tsx
  src/components/auth/KakaoOAuthHandler.tsx
  src/components/auth/SocialLoginButton.tsx
  src/components/header/MainLogoHeader.tsx
  src/constants/constants.ts
  src/hooks/useAuth.ts
  src/hooks/useAuthHandler.ts
  src/hooks/useUsers.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/SplashPage.tsx
  src/routes/Router.tsx
  src/types/user.ts
Labels: 💻 FE, 🚀 FEAT

#69 feat: 존재하지 않는 페이지로 이동할 경우 not found page 렌더링 (#67)
  src/assets/warning.svg
  src/layout/Layout.tsx
  src/pages/AuthorDetailPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/VideoDetailPage.tsx
  src/pages/playlist/PlayListDetailPage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#71 feat: supabase에서 영상 데이터 가져오기 (#66)
  src/api/users.ts
  src/api/videos.ts
  src/components/skeleton/author/AuthorProfileSkeleton.tsx
  src/components/skeleton/video/VideoItemSkeleton.tsx
  src/components/skeleton/video/VideoListSkeleton.tsx
  src/hooks/useUsers.tsx
  src/hooks/useVideos.tsx
  src/pages/AuthorDetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/VideoDetailPage.tsx
  src/types/video.ts
  src/utils/getTimeAgo.ts
Labels: 💻 FE, 🚀 FEAT

#74 refactor: 동영상 추가 페이지 URL 추가 기능 개발 (#65)
  package-lock.json
  package.json
  src/components/common/label-input/LabelInput.tsx
  src/components/video/VideoUploadBox.tsx
  src/constants/constants.ts
Labels: 💻 FE, 🔨 REFACTOR

#77 feat: 영상 상세 페이지에서 댓글 추가, 조회 구현 (#72)
  package-lock.json
  package.json
  src/App.tsx
  src/api/comments.ts
  src/components/comment/CommentActions.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/CommentSubmitForm.tsx
  src/components/comment/VideoComment.tsx
  src/components/video/VideoStats.tsx
  src/hooks/useComments.tsx
  src/store/useCommentStore.ts
  src/types/comment.ts
  src/utils/toast.ts
Labels: 💻 FE, 🚀 FEAT

#79 feat: 북마크 목록, 카테고리 동영상 불러오기 (#75)
  src/api/Categories.ts
  src/api/users.ts
  src/api/videos.ts
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/playlist/PlayList.tsx
  src/components/playlist/PlayListItem.tsx
  src/components/playlist/PlayListVideo.tsx
  src/hooks/useAuth.ts
  src/hooks/useAuthHandler.ts
  src/hooks/useCategories.ts
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/playlist/PlayListDetailPage.tsx
  src/types/playList.ts
Labels: 💻 FE, 🚀 FEAT

#82 feat: 북마크 카테고리 저장 기능 구현 (#80)
  src/api/categories.ts
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/utils/getTimeNow.ts
Labels: 🚀 FEAT

#83 feat: 영상 상세 페이지에서 동영상 url에 따른 임베드 (#81)
  src/components/video/EmbedYoutubeVideo.tsx
  src/components/video/VideoItem.tsx
  src/components/video/VideoUploadBox.tsx
  src/constants/constants.ts
  src/utils/getYoutubeVideoId.ts
Labels: 💻 FE, 🚀 FEAT

#86 feat: 내 정보 페이지 supabase 데이터 적용(# 76)
  src/api/users.ts
  src/api/videos.ts
  src/components/my-page/MyPageVideoItem.tsx
  src/components/my-page/MyPageVideoStats.tsx
  src/components/skeleton/my-page/MyPageProfileSkeleton.tsx
  src/components/skeleton/my-page/MyPageVideoItemSkeleton.tsx
  src/components/skeleton/my-page/MyPageVideoListSkeleton.tsx
  src/hooks/useUsers.tsx
  src/hooks/useVideos.tsx
  src/pages/my-page/MyPage.tsx
  src/store/useUserStore.ts
  src/types/user.ts
Labels: 💻 FE, 🚀 FEAT

#89 feat: 인증되지 않은 유저는 인가되지 않도록 보호된 라우터 구성 (#87)
  src/api/users.ts
  src/components/common/spinner/Spinner.tsx
  src/components/empty/EmptyResult.tsx
  src/components/my-page/MyPageProfile.tsx
  src/layout/Layout.tsx
  src/pages/SplashPage.tsx
  src/pages/my-page/MyPage.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#85 feat: 카테고리 추가시 Toast 알림 및 유효성 검사 추가 (#84)
  package-lock.json
  package.json
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/schema/categorySchema.ts
  tsconfig.json
Labels: 💻 FE, 🚀 FEAT

#92 refactor: 실제 로그인한 유저로 댓글 달도록 수정 (#90)
  src/api/comments.ts
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
Labels: 💻 FE, 🔨 REFACTOR

#93 feat: 운동할 때 듣기 좋은 플리 supabase 연동 (#91)
  src/api/musics.ts
  src/components/playlist/PlayMusicList.tsx
  src/hooks/useMusics.ts
  src/pages/playlist/PlayListDetailPage.tsx
  src/pages/playlist/PlayListPage.tsx
Labels: 💻 FE, 🚀 FEAT

#99 feat: 동영상 업로드 페이지 기능 구현 및 supabse연동 (#88)
  src/api/videos.ts
  src/components/my-page/MyPageVideoCategories.tsx
  src/components/thumbnail/ThumbnailUpload.tsx
  src/components/video/VideoUploadBox.tsx
  src/hooks/useSelectImage.ts
  src/hooks/useVideoCategories.ts
  src/hooks/useVideos.tsx
  src/mocks/videoCategories.ts
  src/pages/VideoAddPage.tsx
  src/schema/videoUploadSchema.ts
  src/types/video.ts
Labels: 💻 FE, 🚀 FEAT

#102 refactor: 내 정보 페이지 내가 업로드한 동영상 로직 수정 (#101)
  src/api/videos.ts
  src/hooks/useVideos.tsx
  src/pages/my-page/MyPage.tsx
Labels: 💻 FE, 🔨 REFACTOR

#104 refactor: user1을 로그인한 id로 대체 (#100)
  src/components/bookmark/BookmarkCategoryList.tsx
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/pages/playlist/PlayListDetailPage.tsx
Labels: 🔨 REFACTOR

#106 feat: useInfiniteQuery를 사용해 영상 무한 스크롤 구현 (#97)
  package-lock.json
  package.json
  src/api/videos.ts
  src/components/playlist/PlayListItem.tsx
  src/constants/constants.ts
  src/hooks/useComments.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useUsers.ts
  src/hooks/useVideos.ts
  src/hooks/useVideos.tsx
  src/pages/AuthorDetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/VideoDetailPage.tsx
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/my-page/MyPage.tsx
Labels: 💻 FE, 🚀 FEAT

#108 feat: 내가 업로드한 동영상 페이지 supabase 연동 (#103)
  src/api/videos.ts
  src/components/my-page/MyUploadVideoItem.tsx
  src/hooks/useVideos.ts
  src/pages/my-page/MyUploadVideoPage.tsx
Labels: 💻 FE, 🚀 FEAT

#110 feat: 영상 좋아요 버튼 supabase와 연동 (#107)
  src/api/video-likes.ts
  src/components/video/VideoStats.tsx
  src/hooks/useBookmarks.ts
  src/hooks/useVideoLikes.ts
Labels: 💻 FE, 🚀 FEAT

#112 refactor: 아이템을 현재 로그인한 사용자에 맞게 제공 (#105)
  src/api/bookmarks.ts
  src/api/videos.ts
  src/components/bookmark/BookmarkItem.tsx
  src/components/bookmark/BookmarkList.tsx
  src/components/bookmark/BookmarkStatus.tsx
  src/components/playlist/PlayList.tsx
  src/components/playlist/PlayListItem.tsx
  src/hooks/useBookmarks.ts
  src/hooks/useVideos.ts
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/pages/bookmark/BookmarkPage.tsx
Labels: 🚀 FEAT, 🔨 REFACTOR

#114 feat: 작성자 팔로우 관련해서 supabase와 연동 (#111)
  src/api/user-follow.ts
  src/api/video-likes.ts
  src/components/author/AuthorProfile.tsx
  src/components/video/VideoItem.tsx
  src/hooks/useFollow.ts
  src/hooks/useVideoLikes.ts
  src/pages/AuthorDetailPage.tsx
Labels: 💻 FE, 🚀 FEAT

#113 feat: 영상 수정 페이지 supabase 연동 및 수정 로직 추가 (#109)
  src/api/videos.ts
  src/components/skeleton/video/VideoEditSkeleton.tsx
  src/components/video/VideoUploadBox.tsx
  src/hooks/useVideos.ts
  src/pages/VideoEditPage.tsx
  src/types/video.ts
Labels: 💻 FE, 🚀 FEAT

#118 feat: 마이페이지 상단에 로그아웃 버튼 추가 후 로직 적용 (#116)
  src/components/auth/LogoutButton.tsx
  src/components/header/LogoHeader.tsx
Labels: 💻 FE, 🚀 FEAT

#120 feat: 북마크 상세 페이지에서 수정과 삭제 기능 구현 (#115)
  src/api/categories.ts
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/playlist/PlayList.tsx
  src/components/playlist/PlayListVideo.tsx
  src/hooks/useCategories.ts
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/pages/playlist/PlayListDetailPage.tsx
  src/types/playList.ts
Labels: 💻 FE, 🚀 FEAT

#121 feat: 영상 상세 페이지에서 본인이 작성한 댓글이라면 삭제할 수 있도록 구현 (#119)
  src/api/comments.ts
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/VideoComment.tsx
  src/hooks/useComments.ts
  src/types/comment.ts
Labels: 💻 FE, 🚀 FEAT

#125 refactor: input 컴포넌트에 디바운싱 로직 일부 수정 (#124)
  src/components/common/label-input/LabelInput.tsx
  src/hooks/useDebounce.ts
Labels: 💻 FE, 🔨 REFACTOR

#122 feat: 내 정보 수정 페이지 supabase 연동 및 로직 추가(#117)
  src/api/users.ts
  src/hooks/useUsers.ts
  src/hooks/useVideos.ts
  src/pages/my-page/MyPageEdit.tsx
  src/schema/profileSchema.ts
Labels: 💻 FE, 🚀 FEAT

#127 feat: 프리텐다드 폰트 파일 추가 (#126)
  index.html
  public/favicon.ico
  public/fonts/Pretendard-Bold.subset.woff
  public/fonts/Pretendard-Bold.subset.woff2
  public/fonts/Pretendard-Light.subset.woff
  public/fonts/Pretendard-Light.subset.woff2
  public/fonts/Pretendard-Medium.subset.woff
  public/fonts/Pretendard-Medium.subset.woff2
  public/fonts/Pretendard-Regular.subset.woff
  public/fonts/Pretendard-Regular.subset.woff2
  src/styles/font.css
  src/styles/global.css
  tailwind.config.js
Labels: 💻 FE, 🚀 FEAT

#129 feat: 내 정보 페이지 내가 시청한 영상, 내가 좋아요한 영상으로 변경 (#128)
  src/api/video-likes.ts
  src/components/skeleton/my-page/MyPageSkeleton.tsx
  src/hooks/useVideoLikes.ts
  src/pages/my-page/MyPage.tsx
Labels: 💻 FE, 🚀 FEAT

#132 docs: 프로젝트 README 작성 (#131)
  README.md
Labels: 💻 FE

#135 feat: 댓글 개수에서 댓글과 대댓글 개수를 합쳐서 표현 (#133)
  src/api/comments.ts
  src/components/comment/VideoComment.tsx
  src/components/video/VideoStats.tsx
  src/hooks/useComments.ts
  src/types/comment.ts
Labels: 💻 FE, 🚀 FEAT

#134 feat: 내 정보 페이지 내 댓글 구현 (#76)
  src/api/comments.ts
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/VideoComment.tsx
  src/components/my-page/MyPageUserComments.tsx
  src/components/my-page/MyPageVideoItem.tsx
  src/components/my-page/MyUploadVideoItem.tsx
  src/hooks/useComments.ts
  src/hooks/useVideos.ts
  src/pages/my-page/MyPage.tsx
Labels: 💻 FE, 🚀 FEAT

#130 refactor: 북마크 페이지, 플레이리스트 페이지 UI와 스켈레톤 구현 (#123)
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/bookmark/BookmarkItem.tsx
  src/components/bookmark/BookmarkList.tsx
  src/components/bookmark/BookmarkStatus.tsx
  src/components/playlist/PlayList.tsx
  src/components/playlist/PlayListItem.tsx
  src/components/playlist/PlayMusicList.tsx
  src/components/skeleton/bookmark/BookmarkCategorySkeleton.tsx
  src/components/skeleton/bookmark/BookmarkItemSkeleton.tsx
  src/components/skeleton/music/MusicItemSkeleton.tsx
  src/components/skeleton/music/MusicSkeleton.tsx
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/playlist/PlayListDetailPage.tsx
  src/pages/playlist/PlayListPage.tsx
Labels: 💻 FE, 🔨 REFACTOR

#137 feat: 영상 순서 조정시 supabase 반영 (#136)
  src/api/categories.ts
  src/components/playlist/PlayList.tsx
Labels: 💻 FE, 🚀 FEAT

#145 chore: playwright 초기 세팅 (#144)
  .gitignore
  e2e/tests-examples/demo-todo-app.spec.ts
  e2e/tests/example.spec.ts
  package-lock.json
  package.json
  playwright.config.ts
  src/apis/.gitkeep
  tsconfig.node.json
Labels: 🔧 CHORE

#151 fix: zustand 적용한 영상 수정페이지 새로고침 시 데이터를 불러올 수 없던 오류 수정 (#147)
  src/components/auth/LogoutButton.tsx
  src/components/skeleton/my-page/MyUploadVideoItem.tsx
  src/components/skeleton/my-page/MyUploadVideoListSkeleton.tsx
  src/pages/my-page/MyUploadVideoPage.tsx
  src/store/useUserStore.ts
Labels: 💻 FE, 🚨 HOTFIX

#150 fix: 카테고리 수정시 기존 동영상 로드 (#149)
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
Labels: 💣 BUG, 🚨 HOTFIX

#152 test: playwright를 통한 소셜 로그인 테스트 코드 추가 (#146)
  e2e/tests/login.spec.ts
Labels: 🔍 TEST

#142 fix: 내 정보 페이지와 영상 수정 페이지에서 발생한 오류 수정 (#141)
  src/components/my-page/MyPageUploadVideoList.tsx
  src/components/my-page/WatchedVideoList.tsx
  src/pages/VideoEditPage.tsx
  src/pages/my-page/MyPage.tsx
Labels: 💻 FE, 🚨 HOTFIX

#154 hotfix : PlayListDetailPage에서 발생한 unique "key" 오류를 해결합니다 (#153)
  src/pages/playlist/PlayListDetailPage.tsx
Labels: 🚨 HOTFIX

#155 fix: react-beautiful-dnd 라이브러리 사용시 Support for defaultProps will be removed warning 해결 (#70)
  package-lock.json
  package.json
  src/components/playlist/PlayList.tsx
Labels: 🚨 HOTFIX

#157 refactor: 북마크페이지에서 전체 카테고리 제거 (#156)
  src/mocks/bookmarkCategories.ts
  src/pages/bookmark/BookmarkPage.tsx
Labels: 💻 FE, 🔨 REFACTOR

#160 feat: 댓글 좋아요/싫어요 supabse 연동 (#78)
  src/api/comments-thumb.ts
  src/components/comment/CommentActions.tsx
  src/components/comment/CommentItem.tsx
  src/hooks/useCommentsThumb.ts
  src/types/comment.ts
Labels: 💻 FE, 🚀 FEAT

#161 refactor: 영상 업로드, 수정 페이지 컴포넌트화 (#158)
  src/components/my-page/MyPageVideoCategories.tsx
  src/components/video-upload-form/VideoCategoriesForm.tsx
  src/components/video-upload-form/VideoThumnailForm.tsx
  src/components/video-upload-form/VideoTitleForm.tsx
  src/components/video-upload-form/VideoUploadForm.tsx
  src/components/video-upload-form/VideoUrlForm.tsx
  src/hooks/useVideoCategories.ts
  src/hooks/useVideos.ts
  src/pages/VideoAddPage.tsx
  src/pages/VideoEditPage.tsx
  src/types/video.ts
Labels: 💻 FE, 🔨 REFACTOR

#164 refactor: splash 시간을 1초에서 2초로 변경 (#163)
  src/pages/SplashPage.tsx
Labels: 💻 FE, 🔨 REFACTOR

#162 refactor: 플레이리스트 페이지 팔로우한 사람 플리도 공유 (#159)
  src/api/categories.ts
  src/api/user-follow.ts
  src/components/bookmark/BookmarkCategoryItem.tsx
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/playlist/PlayMusicList.tsx
  src/hooks/useCategories.ts
  src/hooks/useFollow.ts
  src/pages/playlist/PlayListDetailPage.tsx
  src/pages/playlist/PlayListPage.tsx
Labels: 💻 FE, 🔨 REFACTOR

#168 refactor: 내 정보 수정 페이지 컴포넌트화 (#167)
  src/components/auth/LogoutButton.tsx
  src/components/my-page/MyPageEditForm.tsx
  src/pages/my-page/MyPageEdit.tsx
Labels: 💻 FE, 🔨 REFACTOR, 🌴 STYLE

#170 fix: 플레이리스트 페이지 렌더링 문제를 해결합니다 (#165)
  src/components/bookmark/BookmarkCategoryItem.tsx
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/playlist/PlayMusicList.tsx
  src/components/skeleton/bookmark/BookmarkPlayListSkeleton.tsx
  src/pages/playlist/PlayListPage.tsx
Labels: 💣 BUG

#172 style: 스켈레톤 스타일 수정 (#171)
  src/components/bookmark/BookmarkList.tsx
  src/components/bookmark/BookmarkStatus.tsx
  src/components/my-page/MyPageUserComments.tsx
  src/components/my-page/MyPageVideoItem.tsx
  src/components/my-page/MyUploadVideoItem.tsx
  src/components/playlist/PlayListItem.tsx
  src/components/skeleton/bookmark/BookmarkCategoryAddSkeleton.tsx
  src/components/skeleton/bookmark/BookmarkItemSkeleton.tsx
  src/components/skeleton/music/MusicItemSkeleton.tsx
  src/components/skeleton/my-page/MyPageProfileSkeleton.tsx
  src/components/skeleton/my-page/MyPageSkeleton.tsx
  src/components/skeleton/my-page/MyPageVideoItemSkeleton.tsx
  src/components/skeleton/my-page/MyPageVideoListSkeleton.tsx
  src/components/skeleton/my-page/MyUploadVideoItem.tsx
  src/components/skeleton/my-page/MyUploadVideoListSkeleton.tsx
  src/pages/my-page/MyPage.tsx
Labels: 💻 FE, 🌴 STYLE

#176 hotfix: 팔로우한 유저가 없을 때 플레이리스트가 조회되지 않았던 오류 (#174)
  src/components/bookmark/BookmarkCategoryList.tsx
  src/components/bookmark/BookmarkItem.tsx
Labels: 🚨 HOTFIX

#179 style: BookmarkItem에서 figure와 img에 적용한 h-full 옵션 삭제 (#177)
  src/components/bookmark/BookmarkItem.tsx
Labels: 🌴 STYLE

#180 style: 메인 로고, 하단 네비게이션바 스타일 수정 (#178)
  src/components/header/MainLogoHeader.tsx
  src/components/navigation-bar/NavigationBar.tsx
Labels: 🌴 STYLE

#182 refactor: 동영상 미 클릭시 에러 메시지 출력 (#181)
  src/pages/bookmark/BookmarkCategoryAddPage.tsx
Labels: 🔨 REFACTOR
